[
 { "cc_library": {
     "name" : "parser",
     "cc_sources" : [ "parser.cc" ],
     "cc_headers" : [ "parser.h" ],
     "dependencies": [ "//common/log:log",
                       "//common/file:fileutil",
                       "//common/strings:path",
                       "//env:input",
                       "//nodes:allnodes",
                       "//jsonxx:jsonxx",
                       "//reader:buildfile",
     ]
   }
 },
]