[
 { "cc_library": {
     "name" : "generator",
     "cc_sources" : [ "generator.cc" ],
     "cc_headers" : [ "generator.h" ],
     "dependencies": [ "//common/log:log",
                       "//env:input",
                       "//nodes:allnodes",
                       "//reader:parser"
     ]
   }
 }
]