# Auto-generated by repobuild, do not modify directly.

obj/repobuild.cc.o: common/base/init.h common/file/fileutil.h common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h env/input.h env/target.h generator/generator.h json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h nodes/allnodes.h nodes/cc_binary.h nodes/cc_library.h nodes/node.h reader/buildfile.h reader/parser.h repobuild.cc
	mkdir -p obj; clang++ -std=c++11 -stdlib=libc++ -pthread -DUSE_CXX0X -g -c -I. repobuild.cc -o obj/repobuild.cc.o

obj/repobuild: obj/common/base/init.cc.o obj/common/file/fileutil.cc.o obj/common/strings/path.cc.o obj/common/strings/re2/stringpiece.cc.o obj/common/strings/strutil.cc.o obj/env/input.cc.o obj/env/target.cc.o obj/generator/generator.cc.o obj/json/json_reader.cpp.o obj/json/json_value.cpp.o obj/json/json_writer.cpp.o obj/nodes/allnodes.cc.o obj/nodes/cc_binary.cc.o obj/nodes/cc_library.cc.o obj/nodes/node.cc.o obj/reader/buildfile.cc.o obj/reader/parser.cc.o obj/repobuild.cc.o
	mkdir -p obj/; clang++ -std=c++11 -stdlib=libc++ -pthread -DUSE_CXX0X -g  obj/common/base/init.cc.o obj/common/file/fileutil.cc.o obj/common/strings/path.cc.o obj/common/strings/re2/stringpiece.cc.o obj/common/strings/strutil.cc.o obj/env/input.cc.o obj/env/target.cc.o obj/generator/generator.cc.o obj/json/json_reader.cpp.o obj/json/json_value.cpp.o obj/json/json_writer.cpp.o obj/nodes/allnodes.cc.o obj/nodes/cc_binary.cc.o obj/nodes/cc_library.cc.o obj/nodes/node.cc.o obj/reader/buildfile.cc.o obj/reader/parser.cc.o obj/repobuild.cc.o -o obj/repobuild

obj/common/base/init.cc.o: common/base/init.h common/base/init.cc
	mkdir -p obj/common/base; clang++ -std=c++11 -stdlib=libc++ -pthread -DUSE_CXX0X -g -c -I. common/base/init.cc -o obj/common/base/init.cc.o

obj/common/file/fileutil.cc.o: common/file/fileutil.h common/log/log.h common/file/fileutil.cc
	mkdir -p obj/common/file; clang++ -std=c++11 -stdlib=libc++ -pthread -DUSE_CXX0X -g -c -I. common/file/fileutil.cc -o obj/common/file/fileutil.cc.o

obj/common/strings/re2/stringpiece.cc.o: common/strings/re2/stringpiece.h common/strings/re2/stringpiece.cc
	mkdir -p obj/common/strings/re2; clang++ -std=c++11 -stdlib=libc++ -pthread -DUSE_CXX0X -g -c -I. common/strings/re2/stringpiece.cc -o obj/common/strings/re2/stringpiece.cc.o

obj/common/strings/strutil.cc.o: common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h common/strings/strutil.cc
	mkdir -p obj/common/strings; clang++ -std=c++11 -stdlib=libc++ -pthread -DUSE_CXX0X -g -c -I. common/strings/strutil.cc -o obj/common/strings/strutil.cc.o

obj/common/strings/path.cc.o: common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h common/strings/path.cc
	mkdir -p obj/common/strings; clang++ -std=c++11 -stdlib=libc++ -pthread -DUSE_CXX0X -g -c -I. common/strings/path.cc -o obj/common/strings/path.cc.o

obj/env/input.cc.o: env/input.h env/input.cc
	mkdir -p obj/env; clang++ -std=c++11 -stdlib=libc++ -pthread -DUSE_CXX0X -g -c -I. env/input.cc -o obj/env/input.cc.o

obj/env/target.cc.o: common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h env/target.h env/target.cc
	mkdir -p obj/env; clang++ -std=c++11 -stdlib=libc++ -pthread -DUSE_CXX0X -g -c -I. env/target.cc -o obj/env/target.cc.o

obj/generator/generator.cc.o: common/file/fileutil.h common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h env/input.h env/target.h generator/generator.h json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h nodes/allnodes.h nodes/cc_binary.h nodes/cc_library.h nodes/node.h reader/buildfile.h reader/parser.h generator/generator.cc
	mkdir -p obj/generator; clang++ -std=c++11 -stdlib=libc++ -pthread -DUSE_CXX0X -g -c -I. generator/generator.cc -o obj/generator/generator.cc.o

obj/json/json_reader.cpp.o: json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h json/json_reader.cpp
	mkdir -p obj/json; clang++ -std=c++11 -stdlib=libc++ -pthread -DUSE_CXX0X -g -c -I. json/json_reader.cpp -o obj/json/json_reader.cpp.o

obj/json/json_value.cpp.o: json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h json/json_value.cpp
	mkdir -p obj/json; clang++ -std=c++11 -stdlib=libc++ -pthread -DUSE_CXX0X -g -c -I. json/json_value.cpp -o obj/json/json_value.cpp.o

obj/json/json_writer.cpp.o: json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h json/json_writer.cpp
	mkdir -p obj/json; clang++ -std=c++11 -stdlib=libc++ -pthread -DUSE_CXX0X -g -c -I. json/json_writer.cpp -o obj/json/json_writer.cpp.o

obj/nodes/allnodes.cc.o: common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h nodes/allnodes.h nodes/cc_binary.h nodes/cc_library.h nodes/node.h reader/buildfile.h nodes/allnodes.cc
	mkdir -p obj/nodes; clang++ -std=c++11 -stdlib=libc++ -pthread -DUSE_CXX0X -g -c -I. nodes/allnodes.cc -o obj/nodes/allnodes.cc.o

obj/nodes/cc_binary.cc.o: common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h nodes/cc_binary.h nodes/node.h reader/buildfile.h nodes/cc_binary.cc
	mkdir -p obj/nodes; clang++ -std=c++11 -stdlib=libc++ -pthread -DUSE_CXX0X -g -c -I. nodes/cc_binary.cc -o obj/nodes/cc_binary.cc.o

obj/nodes/cc_library.cc.o: common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h nodes/cc_library.h nodes/node.h reader/buildfile.h nodes/cc_library.cc
	mkdir -p obj/nodes; clang++ -std=c++11 -stdlib=libc++ -pthread -DUSE_CXX0X -g -c -I. nodes/cc_library.cc -o obj/nodes/cc_library.cc.o

obj/nodes/node.cc.o: common/log/log.h json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h nodes/node.h reader/buildfile.h nodes/node.cc
	mkdir -p obj/nodes; clang++ -std=c++11 -stdlib=libc++ -pthread -DUSE_CXX0X -g -c -I. nodes/node.cc -o obj/nodes/node.cc.o

obj/reader/buildfile.cc.o: common/log/log.h json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h reader/buildfile.h reader/buildfile.cc
	mkdir -p obj/reader; clang++ -std=c++11 -stdlib=libc++ -pthread -DUSE_CXX0X -g -c -I. reader/buildfile.cc -o obj/reader/buildfile.cc.o

obj/reader/parser.cc.o: common/file/fileutil.h common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h env/input.h env/target.h json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h nodes/allnodes.h nodes/cc_binary.h nodes/cc_library.h nodes/node.h reader/buildfile.h reader/parser.h reader/parser.cc
	mkdir -p obj/reader; clang++ -std=c++11 -stdlib=libc++ -pthread -DUSE_CXX0X -g -c -I. reader/parser.cc -o obj/reader/parser.cc.o


