# Auto-generated by repobuild, do not modify directly.

gen-obj/repobuild.cc.o: common/base/init.h common/file/fileutil.h common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h common/strings/varmap.h env/input.h env/target.h gen-src/common/.dummy gen-src/repobuild/.dummy generator/generator.h json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h nodes/allnodes.h nodes/cc_binary.h nodes/cc_library.h nodes/confignode.h nodes/gen_sh.h nodes/go_binary.h nodes/go_library.h nodes/node.h reader/buildfile.h reader/parser.h repobuild.cc
	mkdir -p gen-obj; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 repobuild.cc -o gen-obj/repobuild.cc.o

gen-obj/repobuild: gen-obj/common/base/init.cc.o gen-obj/common/file/fileutil.cc.o gen-obj/common/strings/path.cc.o gen-obj/common/strings/re2/stringpiece.cc.o gen-obj/common/strings/strutil.cc.o gen-obj/common/strings/varmap.cc.o gen-obj/env/input.cc.o gen-obj/env/target.cc.o gen-obj/generator/generator.cc.o gen-obj/json/json_reader.cpp.o gen-obj/json/json_value.cpp.o gen-obj/json/json_writer.cpp.o gen-obj/nodes/allnodes.cc.o gen-obj/nodes/cc_binary.cc.o gen-obj/nodes/cc_library.cc.o gen-obj/nodes/confignode.cc.o gen-obj/nodes/gen_sh.cc.o gen-obj/nodes/go_binary.cc.o gen-obj/nodes/go_library.cc.o gen-obj/nodes/node.cc.o gen-obj/reader/buildfile.cc.o gen-obj/reader/parser.cc.o gen-obj/repobuild.cc.o
	mkdir -p gen-obj; $(CXX) $(CXXFLAGS) -std=c++11 -DUSE_CXX0X -stdlib=libc++ -lpthread -g -O3 gen-obj/common/base/init.cc.o gen-obj/common/file/fileutil.cc.o gen-obj/common/strings/path.cc.o gen-obj/common/strings/re2/stringpiece.cc.o gen-obj/common/strings/strutil.cc.o gen-obj/common/strings/varmap.cc.o gen-obj/env/input.cc.o gen-obj/env/target.cc.o gen-obj/generator/generator.cc.o gen-obj/json/json_reader.cpp.o gen-obj/json/json_value.cpp.o gen-obj/json/json_writer.cpp.o gen-obj/nodes/allnodes.cc.o gen-obj/nodes/cc_binary.cc.o gen-obj/nodes/cc_library.cc.o gen-obj/nodes/confignode.cc.o gen-obj/nodes/gen_sh.cc.o gen-obj/nodes/go_binary.cc.o gen-obj/nodes/go_library.cc.o gen-obj/nodes/node.cc.o gen-obj/reader/buildfile.cc.o gen-obj/reader/parser.cc.o gen-obj/repobuild.cc.o -o gen-obj/repobuild

repobuild: gen-obj/repobuild
	pwd > /dev/null
	ln -f -s gen-obj/repobuild repobuild

gen-src/common:
	mkdir -p gen-src; if [[ ! -a common ]]; then mkdir -p common; fi; ln -f -s ../common gen-src/common

gen-src/common/.dummy: gen-src/common
	if [[ ! -a gen-src/common/.dummy ]]; then touch gen-src/common/.dummy; fi

gen-src/repobuild:
	mkdir -p gen-src; if [[ ! -a . ]]; then mkdir -p .; fi; ln -f -s .. gen-src/repobuild

gen-src/repobuild/.dummy: gen-src/repobuild
	if [[ ! -a gen-src/repobuild/.dummy ]]; then touch gen-src/repobuild/.dummy; fi

gen-obj/common/base/init.cc.o: common/base/init.h gen-src/common/.dummy gen-src/repobuild/.dummy common/base/init.cc
	mkdir -p gen-obj/common/base; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 common/base/init.cc -o gen-obj/common/base/init.cc.o

gen-obj/common/file/fileutil.cc.o: common/file/fileutil.h common/log/log.h gen-src/common/.dummy gen-src/repobuild/.dummy common/file/fileutil.cc
	mkdir -p gen-obj/common/file; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 common/file/fileutil.cc -o gen-obj/common/file/fileutil.cc.o

gen-obj/common/strings/strutil.cc.o: common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h common/strings/varmap.h gen-src/common/.dummy gen-src/repobuild/.dummy common/strings/strutil.cc
	mkdir -p gen-obj/common/strings; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 common/strings/strutil.cc -o gen-obj/common/strings/strutil.cc.o

gen-obj/common/strings/path.cc.o: common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h common/strings/varmap.h gen-src/common/.dummy gen-src/repobuild/.dummy common/strings/path.cc
	mkdir -p gen-obj/common/strings; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 common/strings/path.cc -o gen-obj/common/strings/path.cc.o

gen-obj/common/strings/varmap.cc.o: common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h common/strings/varmap.h gen-src/common/.dummy gen-src/repobuild/.dummy common/strings/varmap.cc
	mkdir -p gen-obj/common/strings; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 common/strings/varmap.cc -o gen-obj/common/strings/varmap.cc.o

gen-obj/env/input.cc.o: common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h common/strings/varmap.h env/input.h gen-src/common/.dummy gen-src/repobuild/.dummy env/input.cc
	mkdir -p gen-obj/env; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 env/input.cc -o gen-obj/env/input.cc.o

gen-obj/generator/generator.cc.o: common/file/fileutil.h common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h common/strings/varmap.h env/input.h env/target.h gen-src/common/.dummy gen-src/repobuild/.dummy generator/generator.h json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h nodes/allnodes.h nodes/cc_binary.h nodes/cc_library.h nodes/confignode.h nodes/gen_sh.h nodes/go_binary.h nodes/go_library.h nodes/node.h reader/buildfile.h reader/parser.h generator/generator.cc
	mkdir -p gen-obj/generator; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 generator/generator.cc -o gen-obj/generator/generator.cc.o

gen-obj/env/target.cc.o: common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h common/strings/varmap.h env/target.h gen-src/common/.dummy gen-src/repobuild/.dummy env/target.cc
	mkdir -p gen-obj/env; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 env/target.cc -o gen-obj/env/target.cc.o

gen-obj/common/strings/re2/stringpiece.cc.o: common/strings/re2/stringpiece.h gen-src/common/.dummy gen-src/repobuild/.dummy common/strings/re2/stringpiece.cc
	mkdir -p gen-obj/common/strings/re2; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 common/strings/re2/stringpiece.cc -o gen-obj/common/strings/re2/stringpiece.cc.o

gen-obj/nodes/node.cc.o: common/file/fileutil.h common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h common/strings/varmap.h gen-src/common/.dummy gen-src/repobuild/.dummy json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h nodes/node.h reader/buildfile.h nodes/node.cc
	mkdir -p gen-obj/nodes; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 nodes/node.cc -o gen-obj/nodes/node.cc.o

gen-obj/nodes/confignode.cc.o: common/file/fileutil.h common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h common/strings/varmap.h gen-src/common/.dummy gen-src/repobuild/.dummy json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h nodes/confignode.h nodes/node.h reader/buildfile.h nodes/confignode.cc
	mkdir -p gen-obj/nodes; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 nodes/confignode.cc -o gen-obj/nodes/confignode.cc.o

gen-obj/nodes/cc_library.cc.o: common/file/fileutil.h common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h common/strings/varmap.h gen-src/common/.dummy gen-src/repobuild/.dummy json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h nodes/cc_library.h nodes/node.h reader/buildfile.h nodes/cc_library.cc
	mkdir -p gen-obj/nodes; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 nodes/cc_library.cc -o gen-obj/nodes/cc_library.cc.o

gen-obj/nodes/cc_binary.cc.o: common/file/fileutil.h common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h common/strings/varmap.h gen-src/common/.dummy gen-src/repobuild/.dummy json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h nodes/cc_binary.h nodes/node.h reader/buildfile.h nodes/cc_binary.cc
	mkdir -p gen-obj/nodes; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 nodes/cc_binary.cc -o gen-obj/nodes/cc_binary.cc.o

gen-obj/nodes/go_library.cc.o: common/file/fileutil.h common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h common/strings/varmap.h gen-src/common/.dummy gen-src/repobuild/.dummy json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h nodes/go_library.h nodes/node.h reader/buildfile.h nodes/go_library.cc
	mkdir -p gen-obj/nodes; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 nodes/go_library.cc -o gen-obj/nodes/go_library.cc.o

gen-obj/nodes/go_binary.cc.o: common/file/fileutil.h common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h common/strings/varmap.h gen-src/common/.dummy gen-src/repobuild/.dummy json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h nodes/go_binary.h nodes/node.h reader/buildfile.h nodes/go_binary.cc
	mkdir -p gen-obj/nodes; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 nodes/go_binary.cc -o gen-obj/nodes/go_binary.cc.o

gen-obj/nodes/gen_sh.cc.o: common/file/fileutil.h common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h common/strings/varmap.h gen-src/common/.dummy gen-src/repobuild/.dummy json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h nodes/gen_sh.h nodes/node.h reader/buildfile.h nodes/gen_sh.cc
	mkdir -p gen-obj/nodes; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 nodes/gen_sh.cc -o gen-obj/nodes/gen_sh.cc.o

gen-obj/nodes/allnodes.cc.o: common/file/fileutil.h common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h common/strings/varmap.h gen-src/common/.dummy gen-src/repobuild/.dummy json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h nodes/allnodes.h nodes/cc_binary.h nodes/cc_library.h nodes/confignode.h nodes/gen_sh.h nodes/go_binary.h nodes/go_library.h nodes/node.h reader/buildfile.h nodes/allnodes.cc
	mkdir -p gen-obj/nodes; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 nodes/allnodes.cc -o gen-obj/nodes/allnodes.cc.o

gen-obj/reader/buildfile.cc.o: common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h common/strings/varmap.h gen-src/common/.dummy gen-src/repobuild/.dummy json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h reader/buildfile.h reader/buildfile.cc
	mkdir -p gen-obj/reader; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 reader/buildfile.cc -o gen-obj/reader/buildfile.cc.o

gen-obj/reader/parser.cc.o: common/file/fileutil.h common/log/log.h common/strings/path.h common/strings/re2/stringpiece.h common/strings/stringpiece.h common/strings/strutil.h common/strings/varmap.h env/input.h env/target.h gen-src/common/.dummy gen-src/repobuild/.dummy json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h nodes/allnodes.h nodes/cc_binary.h nodes/cc_library.h nodes/confignode.h nodes/gen_sh.h nodes/go_binary.h nodes/go_library.h nodes/node.h reader/buildfile.h reader/parser.h reader/parser.cc
	mkdir -p gen-obj/reader; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 reader/parser.cc -o gen-obj/reader/parser.cc.o

gen-obj/json/json_reader.cpp.o: gen-src/repobuild/.dummy json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h json/json_reader.cpp
	mkdir -p gen-obj/json; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 json/json_reader.cpp -o gen-obj/json/json_reader.cpp.o

gen-obj/json/json_value.cpp.o: gen-src/repobuild/.dummy json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h json/json_value.cpp
	mkdir -p gen-obj/json; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 json/json_value.cpp -o gen-obj/json/json_value.cpp.o

gen-obj/json/json_writer.cpp.o: gen-src/repobuild/.dummy json/autolink.h json/config.h json/features.h json/forwards.h json/json.h json/reader.h json/value.h json/writer.h json/json_writer.cpp
	mkdir -p gen-obj/json; $(CXX) $(CXXFLAGS) -c -I. -Igen-files -Igen-src -std=c++11 -DUSE_CXX0X -stdlib=libc++ -pthread -g -Wall -Werror -O3 json/json_writer.cpp -o gen-obj/json/json_writer.cpp.o

clean:
	rm -f gen-src/repobuild/.dummy
	rm -f gen-src/repobuild
	rm -f repobuild
	rm -f gen-src/common/.dummy
	rm -f gen-src/common
	rm -rf gen-obj
	rm -rf gen-files
	rm -rf gen-src

all: repobuild

.PHONY: clean all

.DEFAULT_GOAL=all

