[
 { "cc_library": {
     "name" : "generator",
     "cc_sources" : [ "generator.cc" ],
     "cc_headers" : [ "generator.h" ],
     "dependencies": [ "//common/log:log",
                       "//common/strings:strutil",
                       "//common/util:stl",
                       "//repobuild/distsource:dist_source",
                       "//repobuild/env:input",
                       "//repobuild/env:resource",
                       "//repobuild/nodes:allnodes",
                       "//repobuild/reader:parser"
     ]
   }
 }
]