[
 { "config": {
     "component": "repobuild"
   }
 },

 { "cc_binary": {
   "name": "repobuild",
   "cc_sources": [ "repobuild.cc" ],
   "dependencies": [ "//common/base:base",  // TMP TMP TMP _tcmalloc",
                     "//common/log:log",
                     "//common/file:fileutil",
                     "//common/strings:stringpiece",
                     "//common/strings:strutil",
                     "//repobuild/distsource:dist_source_impl",
                     "//repobuild/env:input",
                     "//repobuild/env:target",
                     "//repobuild/generator:generator"
                   ]
   }
 }
]