# Test objects
[
 { "json": {
     "name" : "json",
     "cc_sources" : [ "json/src/lib_json/json_reader.cpp",
                      "json/src/lib_json/json_value.cpp",
                      "json/src/lib_json/json_writer.cpp"
     ],
     "cc_headers" : [ "json/include/json/autolink.h",
                      "json/include/json/config.h",
                      "json/include/json/features.h",
                      "json/include/json/forwards.h",
                      "json/include/json/json.h",
                      "json/include/json/reader.h",
                      "json/include/json/value.h",
                      "json/include/json/writer.h"
     ],
     cc_include_path: [ "json/include" ]
   }
 },
]