// Test objects
[
 { "config": {
     "component": "c",
     "component_root": "include/c"
 } },

 { "cc_library": {
     "name" : "foo_pred_c",
     "cc_sources" : [ "include/c/foo.cc" ],
     "cc_headers" : [ "include/c/foo.h" ]
   }
 }
]