[
 { "cc_library": {
     "name" : "input",
     "cc_sources" : [ "input.cc" ],
     "cc_headers" : [ "input.h" ],
     "dependencies" : [
       "//common/base:flags",
       "//common/file:fileutil",
       "//common/log:log",
       "//common/strings:strutil",
       "//repobuild/third_party/json:json"
     ]
   }
 },
 { "cc_library": {
     "name" : "resource",
     "cc_sources" : [ "resource.cc" ],
     "cc_headers" : [ "resource.h" ],
     "dependencies" : [
       "//common/strings:strutil"
     ]
   }
 },
 { "cc_library": {
     "name" : "target",
     "cc_sources" : [ "target.cc" ],
     "cc_headers" : [ "target.h" ],
     "dependencies": [
       "//common/log:log",
       "//common/strings:strutil"
     ]
   }
 }
]