[
 { "cc_library": {
     "name" : "input",
     "cc_sources" : [ "input.cc" ],
     "cc_headers" : [ "input.h" ]
   }
 },

 { "cc_library": {
     "name" : "target",
     "cc_sources" : [ "target.cc" ],
     "cc_headers" : [ "target.h" ],
     "dependencies": [
       "//common/log:log",
       "//common/strings:path"
     ]
   }
 }
]