# Test objects
[
 { "cc_library": {
     "name" : "foo_pred_b",
     "cc_sources" : [ "foo.cc" ],
     "cc_headers" : [ "foo.h" ]
   }
 },

 { "cc_library": {
     "name" : "bar_pred_b",
     "cc_sources" : [ "bar.cc" ],
     "dependencies" : [ "//a:bar_pred_a" ]
   }
 }
]